<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="HATI-SDG00096" failures="0" tests="2" name="LabTest.Phlebotomy_Pending_Outsource_Reject_Current_order_Print_and_submit" time="133.479" errors="1" timestamp="2024-09-11T09:59:05 IST" skipped="0">
  <testcase classname="LabTest.Phlebotomy_Pending_Outsource_Reject_Current_order_Print_and_submit" name="TC_02_Phlebotomy_Pending_Outsource_Reject_Current_order_Print_and_submit" time="122.296">
    <error message="Index 2 out of bounds for length 2" type="java.lang.IndexOutOfBoundsException">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
at java.base/java.util.Objects.checkIndex(Objects.java:385)
at java.base/java.util.ArrayList.get(ArrayList.java:427)
at LabPages.Phlebotomy_Pending_Outsource_Reject_Current_order_Print_and_submit.OPD_REGISTRATION(Phlebotomy_Pending_Outsource_Reject_Current_order_Print_and_submit.java:414)
at LabTest.Phlebotomy_Pending_Outsource_Reject_Current_order_Print_and_submit.TC_02_Phlebotomy_Pending_Outsource_Reject_Current_order_Print_and_submit(Phlebotomy_Pending_Outsource_Reject_Current_order_Print_and_submit.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TC_02_Phlebotomy_Pending_Outsource_Reject_Current_order_Print_and_submit -->
  <testcase classname="LabTest.Phlebotomy_Pending_Outsource_Reject_Current_order_Print_and_submit" name="TC_01_verify_That_User_Is_Able_To_Login_MedcareApplication" time="11.183"/>
</testsuite> <!-- LabTest.Phlebotomy_Pending_Outsource_Reject_Current_order_Print_and_submit -->
