<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="HATI-SDG00096" failures="1" tests="2" name="ADTTest.ExistingAdmissionRequest_Advanced_Search_By_Name" time="41.853" errors="0" timestamp="2024-08-05T14:15:37 IST" skipped="0">
  <testcase classname="ADTTest.ExistingAdmissionRequest_Advanced_Search_By_Name" name="TC_01_verify_That_User_Is_Able_To_Login_ADT_Admission_Form_MedcareApplication" time="10.500"/>
  <testcase classname="ADTTest.ExistingAdmissionRequest_Advanced_Search_By_Name" name="TC_02_Verify_That_User_Is_Able_To_Search_Existing_Admission_Record_Through_Advanced_Search_By_MRN" time="31.353">
    <failure message="No patients found matching this search expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No patients found matching this search expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at ADTpages.Existing_Admission_Request_Advanced_Search_By_Name.ADTExistingAdmissionAdvancedSearch_By_Name(Existing_Admission_Request_Advanced_Search_By_Name.java:72)
at ADTTest.ExistingAdmissionRequest_Advanced_Search_By_Name.TC_02_Verify_That_User_Is_Able_To_Search_Existing_Admission_Record_Through_Advanced_Search_By_MRN(ExistingAdmissionRequest_Advanced_Search_By_Name.java:49)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1296)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_02_Verify_That_User_Is_Able_To_Search_Existing_Admission_Record_Through_Advanced_Search_By_MRN -->
</testsuite> <!-- ADTTest.ExistingAdmissionRequest_Advanced_Search_By_Name -->
